### ISSUE TITLE
fsapp: possible race condition w/kombu exchange handling

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc-task#73]
Looks like when running multiple workers processes (and not concurrency within a single worker) it's possible to get simultaneous writes to `reply.celery.pidbox.exchange` which ends up generating invalid json. This leads to json parsing errors when using `inspect()`.

This is not reliably reproducible right now, will need future investigation

```
example-get-started git:master  py:example-get-started ❯ dvc queue status -v                                                                                                                          ⏎
Task     Name    Created    Status
664fb31          03:50 PM   Success
ab4a6b7          03:50 PM   Success
7db2881          03:50 PM   Success

2022-07-05 15:55:47,834 ERROR: unexpected error - Extra data: line 1 column 850 (char 849)
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pmrowla/git/dvc/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/Users/pmrowla/git/dvc/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/pmrowla/git/dvc/dvc/commands/queue/status.py", line 40, in run
    worker_status = self.repo.experiments.celery_queue.worker_status()
  File "/Users/pmrowla/git/dvc/dvc/repo/experiments/queue/celery.py", line 349, in worker_status
    status = self.celery.control.inspect().active() or {}
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/celery/app/control.py", line 149, in active
    return self._request('active', safe=safe)
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/celery/app/control.py", line 741, in broadcast
    return self.mailbox(conn)._broadcast(
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/pidbox.py", line 337, in _broadcast
    self._publish(command, arguments, destination=destination,
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/pidbox.py", line 299, in _publish
    maybe_declare(self.reply_queue(chan))
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/common.py", line 112, in maybe_declare
    return _maybe_declare(entity, channel)
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/common.py", line 152, in _maybe_declare
    entity.declare(channel=channel)
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/entity.py", line 608, in declare
    self._create_queue(nowait=nowait, channel=channel)
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/entity.py", line 619, in _create_queue
    self.queue_bind(nowait=nowait, channel=channel)
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/entity.py", line 662, in queue_bind
    return self.bind_to(self.exchange, self.routing_key,
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/entity.py", line 671, in bind_to
    return (channel or self.channel).queue_bind(
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/transport/virtual/base.py", line 568, in queue_bind
    self._queue_bind(exchange, *meta)
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/transport/filesystem.py", line 193, in _queue_bind
    queues = self.get_table(exchange)
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/transport/filesystem.py", line 187, in get_table
    exchange_table = loads(bytes_to_str(f_obj.read()))
  File "/Users/pmrowla/.virtualenvs/example-get-started/lib/python3.9/site-packages/kombu/utils/json.py", line 97, in loads
    return _loads(s, object_hook=object_hook)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 850 (char 849)
```

**Comment by karajan1001** [comment]
might related to https://github.com/celery/kombu/issues/398

**Comment by pmrowla** [comment]
There's some existing synchronization/file locks in the filesystem transport, but we will probably have to improve it and test it more thoroughly ourselves. But I'd say this is not a high priority need for DVC right now since using `--jobs` for parallelization is still considered experimental.

**Comment by dberenbaum** [comment]
What's the state of parallelization now? It's experimental but was hoping that dvc-task would make it more stable, and last I checked it seemed less stable. We don't want it to be experimental indefinitely, and it seems natural to use it with the more robust queue. Is it worth adding it as a housekeeping task to stabilize it?

**Comment by pmrowla** [comment]
@dberenbaum it's probably worth adding as a housekeeping task. In general it should end up being more stable, but there are probably more bugs like this one we will have to clean up in kombu/celery, just because we are using it in a non-standard way (since we run celery using the filesystem broker rather than a traditional messaging server)

**Comment by karajan1001** [comment]
```
Traceback (most recent call last):
  File "/Users/gao/Code/dvc/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/gao/Code/dvc/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/gao/Code/dvc/dvc/repo/experiments/queue/tasks.py", line 118, in run_exp
    root_dir = setup_exp.s(entry_dict)()
  File "/Users/gao/Code/dvc/.venv/lib/python3.10/site-packages/celery/canvas.py", line 168, in __call__
    return self.type(*args, **kwargs)
  File "/Users/gao/Code/dvc/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 735, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/Users/gao/Code/dvc/.venv/lib/python3.10/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
  File "/Users/gao/Code/dvc/dvc/repo/experiments/queue/tasks.py", line 31, in setup_exp
    executor = BaseStashQueue.setup_executor(
  File "/Users/gao/Code/dvc/dvc/repo/experiments/utils.py", line 39, in wrapper
    with map_scm_exception(), exp.scm_lock:
  File "/Users/gao/Code/dvc/dvc/lock.py", line 142, in __enter__
    self.lock()
  File "/Users/gao/Code/dvc/dvc/lock.py", line 125, in lock
    lock_retry()
  File "/Users/gao/Code/dvc/.venv/lib/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/gao/Code/dvc/.venv/lib/python3.10/site-packages/funcy/flow.py", line 127, in retry
    return call()
  File "/Users/gao/Code/dvc/.venv/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/gao/Code/dvc/dvc/lock.py", line 119, in _do_lock
    raise LockError(FAILED_TO_LOCK_MESSAGE)
dvc.lock.LockError: Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
```
After I add the new version of `kombu` I got this.
